name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [windows-latest]
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      EXE_NAME: Onmyoji_Python

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Run Pytest
        run: |
          cd tests
          poetry run pytest -s
      
      - name: Build
        run: |
            poetry run pyinstaller main.spec --clean --noconfirm --distpath .
            dir
            cd output
            dir
            cd ..\src\resource\
            dir
      
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXE_NAME }}
          path: |
            output
            buzhihuo.ico
            src\resource\